markdown: kramdown
permalink: /:title/
url: https://blog.nayuom.com
name: blog.nayuom.com
author: n/a
qq: 7558959
email: 
beian: 
cnzz: 
weibo: 
github: bin64
safe: true
paginate: 20
about: "blog.nayuom.com"
