markdown: kramdown
permalink: /:title/
url: https://blog.nayuom.com
name: blog.nayuom.com
author: n/a
qq: n/a
email: n/a
beian: 
cnzz: 
weibo: n/a
github: bin64
safe: true
paginate: 20
about: "blog.nayuom.com"
